// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHQSFuRnUszrTdmrsA8y3JebQiYfPIyPQ',
    appId: '1:79320910267:web:f12a962941ac8991d85c9e',
    messagingSenderId: '79320910267',
    projectId: 'qualitysystem-74ae9',
    authDomain: 'qualitysystem-74ae9.firebaseapp.com',
    storageBucket: 'qualitysystem-74ae9.firebasestorage.app',
    measurementId: 'G-B9SJVCR0VC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjntqwITq9KqVMQy_8bq85bCl3oXPIRBY',
    appId: '1:79320910267:android:485f7ce4ea86e11bd85c9e',
    messagingSenderId: '79320910267',
    projectId: 'qualitysystem-74ae9',
    storageBucket: 'qualitysystem-74ae9.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHQSFuRnUszrTdmrsA8y3JebQiYfPIyPQ',
    appId: '1:79320910267:web:45e9afd2bee7286dd85c9e',
    messagingSenderId: '79320910267',
    projectId: 'qualitysystem-74ae9',
    authDomain: 'qualitysystem-74ae9.firebaseapp.com',
    storageBucket: 'qualitysystem-74ae9.firebasestorage.app',
    measurementId: 'G-J4HZR852YX',
  );
}
